--Create table
USE SCHEMA IMT577_DW_NICHOLAS_FANG.PUBLIC;
CREATE OR REPLACE TABLE FACT_SALESACTUAL (
    DIMPRODUCTID            NUMBER CONSTRAINT FK_DIMPRODUCTID FOREIGN KEY REFERENCES DIM_PRODUCT(DIMPRODUCTID) NOT NULL
    ,DIMSTOREID             NUMBER CONSTRAINT FK_DIMSTOREID FOREIGN KEY REFERENCES DIM_STORE(DIMSTOREID) NOT NULL
    ,DIMRESELLERID          NUMBER CONSTRAINT FK_DIMRESELLERID FOREIGN KEY REFERENCES DIM_RESELLER(DIMRESELLERID) NOT NULL
    ,DIMCUSTOMERID          NUMBER CONSTRAINT FK_DIMCUSTOMERID FOREIGN KEY REFERENCES DIM_CUSTOMER(DIMCUSTOMERID) NOT NULL
    ,DIMCHANNELID           NUMBER CONSTRAINT FK_CHANNELID FOREIGN KEY REFERENCES DIM_CHANNEL(DIMCHANNELID) NOT NULL
    ,DIMSALESDATEID         NUMBER(9) CONSTRAINT FK_DIMTARGETDATEID FOREIGN KEY REFERENCES DIM_DATE(DATE_PKEY) NOT NULL
    ,DIMLOCATIONID          NUMBER CONSTRAINT FK_DIMLOCATIONIDFACTSA FOREIGN KEY REFERENCES DIM_LOCATION(DIMLOCATIONID) NOT NULL
    ,SOURCESALESHEADERID    NUMBER
    ,SOURCESALESDETAILID    NUMBER
    ,SALESAMOUNT            FLOAT
    ,SALESQUANTITY          NUMBER
    ,SALESUNITPRICE         FLOAT
    ,SALESEXTENDEDCOST      FLOAT
    ,SALESTOTALPROFIT       FLOAT
)

--Load unknowns
INSERT INTO FACT_SALESACTUAL (
    DIMPRODUCTID
    ,DIMSTOREID
    ,DIMRESELLERID
    ,DIMCUSTOMERID
    ,DIMCHANNELID
    ,DIMSALESDATEID
    ,DIMLOCATIONID
    ,SOURCESALESHEADERID
    ,SOURCESALESDETAILID
    ,SALESAMOUNT
    ,SALESQUANTITY
    ,SALESUNITPRICE
    ,SALESEXTENDEDCOST
    ,SALESTOTALPROFIT
)
VALUES (
    -1
    ,-1
    ,-1
    ,-1
    ,-1
    ,-1
    ,-1
    ,-1
    ,-1
    ,-1
    ,-1
    ,-1
    ,-1
    ,-1
)

--Load data
INSERT INTO FACT_SALESACTUAL (
    DIMPRODUCTID
    ,DIMSTOREID
    ,DIMRESELLERID
    ,DIMCUSTOMERID
    ,DIMCHANNELID
    ,DIMSALESDATEID
    ,DIMLOCATIONID
    ,SOURCESALESHEADERID
    ,SOURCESALESDETAILID
    ,SALESAMOUNT
    ,SALESQUANTITY
    ,SALESUNITPRICE
    ,SALESEXTENDEDCOST
    ,SALESTOTALPROFIT
)
SELECT
    NVL(SD.PRODUCTID,-1) AS DIMPRODUCTID
    ,NVL(S.DIMSTOREID,-1) AS DIMSTOREID          --S.DIMSTOREID
    ,NVL(R.DIMRESELLERID,-1) AS DIMRESELLERID    --R.DIMRESELLERID
    ,NVL(CU.DIMCUSTOMERID,-1) AS DIMCUSTOMERID
    ,NVL(C.DIMCHANNELID,-1) AS DIMCHANNELID
    ,NVL(D.DATE_PKEY,-1) AS DIMSALESDATEID
    ,CASE -- LOCATION
        WHEN DIMSTOREID != -1 THEN SL.DIMLOCATIONID
        WHEN DIMRESELLERID != -1 THEN RL.DIMLOCATIONID
        ELSE CUL.DIMLOCATIONID
     END AS DIMLOCATIONID
    ,SD.SALESHEADERID AS SOURCESALESHEADERID
    ,SD.SALESDETAILID AS SOURCESALESDETAILID
    ,SD.SALESAMOUNT
    ,SD.SALESQUANTITY
    ,CASE
        WHEN SH.STOREID IS NOT NULL OR SH.CHANNELID = 2 THEN P.PRODUCTRETAILPRICE
        WHEN SH.RESELLERID IS NOT NULL THEN P.PRODUCTWHOLESALEPRICE
     END AS SALESUNITPRICE
    ,P.PRODUCTCOST AS SALESEXTENDEDCOST
    ,((SALESUNITPRICE-SALESEXTENDEDCOST)*SALESQUANTITY) AS SALESTOTALPROFIT

FROM STAGE_SALESDETAIL AS SD 
LEFT JOIN STAGE_SALESHEADER AS SH
    ON SD.SALESHEADERID = SH.SALESHEADERID
LEFT JOIN DIM_PRODUCT AS P
    ON SD.PRODUCTID = P.DIMPRODUCTID
LEFT JOIN DIM_DATE AS D
    ON SH.DATE = D.DATE

LEFT JOIN DIM_STORE AS S
    ON SH.STOREID = S.DIMSTOREID
--STORE AND LOCATION
LEFT JOIN DIM_LOCATION AS SL
    ON S.DIMLOCATIONID = SL.DIMLOCATIONID

LEFT JOIN DIM_RESELLER AS R
    ON R.SOURCERESELLERID = SH.RESELLERID
--RESELLER AND LOCATION
LEFT JOIN DIM_LOCATION AS RL
    ON R.DIMLOCATIONID = RL.DIMLOCATIONID

LEFT JOIN DIM_CUSTOMER as CU
    on CU.SOURCECUSTOMERID = SH.CUSTOMERID
--CUSTOMER AND LOCATION
LEFT JOIN DIM_LOCATION AS CUL
    ON CU.DIMLOCATIONID = CUL.DIMLOCATIONID


LEFT JOIN DIM_CHANNEL AS C
    ON SH.CHANNELID = C.DIMCHANNELID


-- ERROR: Numeric value '10418299-2934-4ca3-b368-d0dfcde58a51' is not recognized
-- THINK THE ERROR HAS TO BE ON THE JOIN FOR DIM_RESELLER??
-- Fixed, populated the TABLE
-- But not sure if this is correct at all