--Create Fact_ProductSalesTarget
USE SCHEMA IMT577_DW_NICHOLAS_FANG.PUBLIC;
CREATE OR REPLACE TABLE FACT_PRODUCTSALESTARGET (
    DIMPRODUCTID                    NUMBER CONSTRAINT FK_DIMPRODUCTID FOREIGN KEY REFERENCES DIM_PRODUCT(DIMPRODUCTID) NOT NULL
    ,DIMTARGETDATEID                NUMBER(9) CONSTRAINT FK_DIMTARGETDATEID FOREIGN KEY REFERENCES DIM_DATE(DATE_PKEY) NOT NULL
    ,PRODUCTTARGETSALESQUANTITY     NUMBER
)

--Load unknown
INSERT INTO FACT_PRODUCTSALESTARGET (
    DIMPRODUCTID
    ,DIMTARGETDATEID
    ,PRODUCTTARGETSALESQUANTITY
)
VALUES (
    -1
    ,-1
    ,-1
)

--Load Data
INSERT INTO FACT_PRODUCTSALESTARGET (
    DIMPRODUCTID
    ,DIMTARGETDATEID
    ,PRODUCTTARGETSALESQUANTITY
)
SELECT 
    TDP.PRODUCTID AS DIMPRODUCTID
    ,D.DATE_PKEY AS DIMTARGETDATEID
    ,TDP.SALESQUANTITYTARGET AS PRODUCTTARGETSALESQUANTITY
FROM STAGE_TDPRODUCT AS TDP
LEFT JOIN DIM_DATE AS D
    ON TDP.YEAR = D.YEAR 
ORDER BY DIMPRODUCTID ASC

