
create or replace table IMT577_DW_NICHOLAS_FANG.PUBLIC.DIM_CHANNEL (
    DIMCHANNELID                INTEGER PRIMARY KEY,
    SOURCECHANNELID             INTEGER,
    SOURCECHANNELCATEGORYID     INTEGER,
    CHANNELNAME                 VARCHAR(255),
    CHANNELCATEGORY             VARCHAR(255)
)

USE SCHEMA IMT577_DW_NICHOLAS_FANG.PUBLIC;
CREATE OR REPLACE TABLE DIM_CUSTOMER (
    DIMCUSTOMERID               INTEGER IDENTITY(1,1) CONSTRAINT PK_DIMCUSTOMERID PRIMARY KEY NOT NULL,
    DIMLOCATIINID               INTEGER CONSTRAINT FK_DIMLOCATIONIDCUSTOMER FOREIGN KEY REFERENCES DIM_LOCATION(DIMLOCATIONID) NOT NULL,
    SOURCECUSTOMERID            VARCHAR(255),
    FULLNAME                    VARCHAR(255),
    FIRSTNAME                   VARCHAR(255),
    LASTNAME                    VARCHAR(255),
    GENDER                      VARCHAR(255),
    EMAILADDRESS                VARCHAR(255),
    PHONENUMBER                 VARCHAR(255)
);

/*
DimLocationID INTEGER CONSTRAINT FK_DimLocationIDCustomer FOREIGN KEY REFERENCES Dim_Location (DimLocationID) NOT NULL
DimLocationID INTEGER CONSTRAINT FK_DimLocationIDReseller FOREIGN KEY REFERENCES Dim_Location (DimLocationID) NOT NULL
USE SCHEMA IMT577_DW_NICHOLAS_FANG.PUBLIC
ALTER TABLE DIM_CUSTOMERS 
  ADD CONSTRAINT FKDIM_CUSTOMERS
    FOREIGN KEY (DIMLOCATIONID) REFERENCES DIM_LOCATION(DIMLOCATIONID)
*/

USE SCHEMA IMT577_DW_NICHOLAS_FANG.PUBLIC;
create or replace table DIM_RESELLER (
    DIMRESELLERID               INT IDENTITY (1,1) CONSTRAINT PK_RESELLERID PRIMARY KEY NOT NULL,
    DIMLOCATIONID               INTEGER CONSTRAINT FK_DIMLOCATIONIDRESELLER FOREIGN KEY REFERENCES DIM_LOCATION(DIMLOCATIONID) NOT NULL,
    SOURCERESELLERID            VARCHAR(255),
    RESELLERNAME                VARCHAR(255),
    CONTACTNAME                 VARCHAR(255),
    PHONENUMBER                 VARCHAR(255),
    EMAIL                       VARCHAR(255)
)

USE SCHEMA IMT577_DW_NICHOLAS_FANG.PUBLIC;
create or replace table DIM_STORE (
    DIMSTOREID                  INT IDENTITY (1,1) CONSTRAINT PK_STOREID PRIMARY KEY NOT NULL,
    DIMLOCATIONID               INTEGER CONSTRAINT FK_DIMLOCATIONIDSTORE FOREIGN KEY REFERENCES DIM_LOCATION(DIMLOCATIONID) NOT NULL,
    SOURCESTOREID               INTEGER,
    STORENUMBER                 VARCHAR(255),
    STOREMANAGER                VARCHAR(255)
)

create or replace table IMT577_DW_NICHOLAS_FANG.PUBLIC.DIM_PRODUCT (
    DIMPRODUCTID                INTEGER,
    SOURCEPRODUCTID             INTEGER,
    SOURCEPRODUCTTYPEID         INTEGER,
    SOURCEPRODUCTCATEGORYID     INTEGER,
    PRODUCTNAME                 VARCHAR(255),
    PRODUCTTYPE                 VARCHAR(255),
    PRODUCTCATEGORY             VARCHAR(255),
    PRODUCTRETAILPRICE          FLOAT,
    PRODUCTWHOLESALEPRICE       FLOAT,
    PRODUCTCOST                 FLOAT,
    PRODUCTRETAILPROFIT         FLOAT,
    PRODUCTWHOLESALEUNITPROFIT  FLOAT,
    PRODUCTPROFITMARGINUNITPERCENT  FLOAT
)

create or replace table IMT577_DW_NICHOLAS_FANG.PUBLIC.DIM_LOCATION (
    DIMLOCATIONID               INT IDENTITY(1,1) CONSTRAINT PK_DIMLOCATIONID PRIMARY KEY NOT NULL, 
    SOURCELOCATIONID            INTEGER,
    POSTALCODE                  VARCHAR(255),
    ADDRESS                     VARCHAR(255),
    CITY                        VARCHAR(255),
    REGION                      VARCHAR(255),
    COUNTRY                     VARCHAR(255)
)


 select * from (
  select
    {{ dbt_utils.surrogate_key(['Address', 'PostalCode']) }} as ID,
    c.ADDRESS,
    c.CITY,
    c.STATEPROVINCE,
    c.COUNTRY,
    c.POSTALCODE
  from {{source('PUBLIC', 'STAGE_CUSTOMER')}} as c
) as customer_locations
union
select * from (
  select
    {{ dbt_utils.surrogate_key(['Address', 'PostalCode']) }} as ID,
    r.ADDRESS,
    r.CITY,
    r.STATEPROVINCE,
    r.COUNTRY,
    r.POSTALCODE
  from {{source('PUBLIC', 'STAGE_RESELLER')}} as r
) as reseller_locations
union
select * from (
  select
    {{ dbt_utils.surrogate_key(['Address', 'PostalCode']) }} as ID,
    s.ADDRESS,
    s.CITY,
    s.STATEPROVINCE,
    s.COUNTRY,
    s.POSTALCODE
  from {{source('PUBLIC', 'STAGE_STORE')}} as s
) as store_locations