--Create table
USE SCHEMA IMT577_DW_NICHOLAS_FANG.PUBLIC;
create or replace table DIM_RESELLER (
    DIMRESELLERID               INT IDENTITY (1,1) CONSTRAINT PK_RESELLERID PRIMARY KEY NOT NULL,
    DIMLOCATIONID               INTEGER CONSTRAINT FK_DIMLOCATIONIDRESELLER FOREIGN KEY REFERENCES DIM_LOCATION(DIMLOCATIONID) NOT NULL,
    SOURCERESELLERID            VARCHAR(255),
    RESELLERNAME                VARCHAR(255),
    CONTACTNAME                 VARCHAR(255),
    PHONENUMBER                 VARCHAR(255),
    EMAILADDRESS                VARCHAR(255)
)

--Load unknown
INSERT INTO DIM_RESELLER (
    DIMRESELLERID,
    DIMLOCATIONID,
    SOURCERESELLERID,
    RESELLERNAME,
    CONTACTNAME,
    PHONENUMBER,
    EMAILADDRESS
)
VALUES(
    -1,
    -1,
    'NA',
    'NA',
    'NA',
    'NA',
    'NA'
);

--Load data
INSERT INTO DIM_RESELLER (
    --DIMRESELLERID,
    DIMLOCATIONID,
    SOURCERESELLERID,
    RESELLERNAME,
    CONTACTNAME,
    PHONENUMBER,
    EMAILADDRESS
)
SELECT
    --DIMRESELLERID
    l.DIMLOCATIONID,
    r.RESLLERID as SOURCERESELLERID, --Spelling error from staging table step
    CASE 
        WHEN r.RESELLERNAME = 'Mississipi Distributors'
        THEN 'Mississippi Distributors'
        ELSE r.RESELLERNAME
    END,
    r.CONTACT as CONTACTNAME,
    r.PHONENUMBER,
    r.EMAILADDRESS
from STAGE_RESELLER as r
left join dim_location as l
  USING (ADDRESS, POSTALCODE)

Select * From DIM_RESELLER