--Create table
USE SCHEMA IMT577_DW_NICHOLAS_FANG.PUBLIC;
CREATE OR REPLACE TABLE DIM_CUSTOMER (
    DIMCUSTOMERID               INTEGER IDENTITY(1,1) CONSTRAINT PK_DIMCUSTOMERID PRIMARY KEY NOT NULL,
    DIMLOCATIONID               INTEGER CONSTRAINT FK_DIMLOCATIONIDCUSTOMER FOREIGN KEY REFERENCES DIM_LOCATION(DIMLOCATIONID) NOT NULL,
    SOURCECUSTOMERID            VARCHAR(255),
    FULLNAME                    VARCHAR(255),
    FIRSTNAME                   VARCHAR(255),
    LASTNAME                    VARCHAR(255),
    GENDER                      VARCHAR(255),
    EMAILADDRESS                VARCHAR(255),
    PHONENUMBER                 VARCHAR(255)
);

--Load unknown
INSERT INTO DIM_CUSTOMER (
    DIMCUSTOMERID,
    DIMLOCATIONID,
    SOURCECUSTOMERID,
    FULLNAME,
    FIRSTNAME,
    LASTNAME,
    GENDER,
    EMAILADDRESS,
    PHONENUMBER
)
VALUES(
    -1,
    -1,
    'NA',
    'NA',
    'NA',
    'NA',
    'NA',
    'NA',
    'NA'
);

--Load data
INSERT INTO DIM_CUSTOMER (
    DIMLOCATIONID,
    SOURCECUSTOMERID,
    FULLNAME,
    FIRSTNAME,
    LASTNAME,
    GENDER,
    EMAILADDRESS,
    PHONENUMBER  
)
SELECT
    --DIM
    l.DIMLOCATIONID as DIMLOCATIONID,
    c.CUSTOMERID as SOURCECUSTOMERID,
    concat(c.FIRSTNAME, ' ', c.LASTNAME) as FULLNAME,
    c.FIRSTNAME as FIRSTNAME,
    c.LASTNAME as LASTNAME,
    c.GENDER as GENDER,
    c.EMAILADDRESS,
    c.PHONENUMBER
from STAGE_CUSTOMER as c
left join dim_location as l
    -- on l.DIMLOCATIONID = c.DIMLOCATIONID
    USING (ADDRESS, POSTALCODE)