/*
    1. Create table
    2. Load unknown
    3. Load Data
*/

USE SCHEMA IMT577_DW_NICHOLAS_FANG.PUBLIC;
create or replace table IMT577_DW_NICHOLAS_FANG.PUBLIC.DIM_CHANNEL (
    DIMCHANNELID                INTEGER PRIMARY KEY,
    SOURCECHANNELID             INTEGER,
    SOURCECHANNELCATEGORYID     INTEGER,
    CHANNELNAME                 VARCHAR(255),
    CHANNELCATEGORY             VARCHAR(255)
);

--Load unknown members
INSERT INTO DIM_CHANNEL (
    DIMCHANNELID,
    SOURCECHANNELID,
    SOURCECHANNELCATEGORYID,
    CHANNELNAME,
    CHANNELCATEGORY 
)
VALUES ( 
     -1
    ,-1
    ,-1 
    ,'Unknown'
    ,'Unknown'
);

--Load data
INSERT INTO DIM_CHANNEL (
    DIMCHANNELID,
    SOURCECHANNELID,
    SOURCECHANNELCATEGORYID,
    CHANNELNAME,
    CHANNELCATEGORY 
)
SELECT
    c.CHANNELID as DIMCHANNELID,
    c.CHANNELID,
    c.CHANNELCATEGORYID,
    c.CHANNEL as CHANNELNAME,
    cat.CHANNELCATEGORY

FROM STAGE_CHANNEL as c
left join STAGE_CHANNELCATEGORY as cat
    on (c.CHANNELCATEGORYID = cat.CHANNELCATEGORYID)
;

SELECT * FROM DIM_CHANNEL