--Create table
USE SCHEMA IMT577_DW_NICHOLAS_FANG.PUBLIC;
create or replace table DIM_STORE (
    DIMSTOREID                  INT IDENTITY (1,1) CONSTRAINT PK_STOREID PRIMARY KEY NOT NULL,
    DIMLOCATIONID               INTEGER CONSTRAINT FK_DIMLOCATIONIDSTORE FOREIGN KEY REFERENCES DIM_LOCATION(DIMLOCATIONID) NOT NULL,
    SOURCESTOREID               INTEGER,
    STORENUMBER                 VARCHAR(255),
    STOREMANAGER                VARCHAR(255)
)

--Load unknown
INSERT INTO DIM_STORE (
    DIMSTOREID,
    DIMLOCATIONID,
    SOURCESTOREID,
    STORENUMBER,
    STOREMANAGER
)
VALUES(
    -1,
    -1,
    -1,
    'NA',
    'NA'
);

--Load data
INSERT INTO DIM_STORE (
    --DIMSTOREID,
    DIMLOCATIONID,
    SOURCESTOREID,
    STORENUMBER,
    STOREMANAGER
)
SELECT
    --DIMSTOREID
    l.DIMLOCATIONID,
    s.STOREID AS SOURCESTOREID,
    s.STORENUMBERID AS STORENUMBER,
    s.STOREMANAGER
FROM STAGE_STORE AS s 
LEFT JOIN DIM_LOCATION AS l 
    USING (ADDRESS, POSTALCODE)
